efault: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *default
  database: test

development:
  <<: *default
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
  database: development

staging:
  <<: *default
  database: staging

production:
  <<: *default
  database: agora_production
  username: agora
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
